In [8]:
import numpy as np
A = np.random.randint(1, 31, size=(3, 3))
print("a:")
print(A)

B = np.full((3, 3), 2)
print("b:")
print(B)

C = np.arange(1, 13).reshape(2, 6)
print("c:")
print(C)

print("d:")
print(A * B)

print("e:")
try:
    e = np.dot(A, C)
    print(e)
except ValueError as e:
    print("Error in matrix multiplication:", e)

mean = np.mean(A)
print("f:")
print("mean A:", mean)

max_A = np.max(A)
print("g:")
print("max A:", max_A)

std_A = np.std(A)
print("h:")
print("std A:", std_A)

flatten_A = A.flatten(order='C')
print("i:")
print("flattened A:", flatten_A)

max_A_axis0 = np.max(A, axis=0)
print("j:")
print("max A along axis 0:", max_A_axis0)

a:
[[19 19 20]
 [ 2 28 27]
 [ 7  4 26]]
b:
[[2 2 2]
 [2 2 2]
 [2 2 2]]
c:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
d:
[[38 38 40]
 [ 4 56 54]
 [14  8 52]]
e:
Error in matrix multiplication: shapes (3,3) and (2,6) not aligned: 3 (dim 1) != 2 (dim 0)
f:
mean A: 16.88888888888889
g:
max A: 28
h:
std A: 9.503735457930265
i:
flattened A: [19 19 20  2 28 27  7  4 26]
j:
max A along axis 0: [19 28 27]


In [13]:
import numpy as np

A = np.arange(3,13)
print("a:")
print(A)

B = np.arange(10, 0, -1)
print("b:")
print(B)

A = A.reshape(2, 5)
print("c:")
print(A)

B = B.reshape(5, 2)
print("d:")
print(B)

e = np.concatenate((A, B.reshape(2, 5)), axis=1)
print("e:")
print(e)

f = np.concatenate((A.reshape(5, 2), B), axis=0)
print("f:")
print(f)

g = np.vsplit(e, 2)
print("g:")
print("ndarray1:", g[0])
print("ndarray2:", g[1])

h = np.hsplit(f, 2)
print("h:")
print("ndarray1:", h[0])
print("ndarray2:", h[1])

i = A.flatten(order='F')
print("i:")
print(i)

j = B.flatten(order='C')
print("j:")
print(j)

a:
[ 3  4  5  6  7  8  9 10 11 12]
b:
[10  9  8  7  6  5  4  3  2  1]
c:
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]
d:
[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
e:
[[ 3  4  5  6  7 10  9  8  7  6]
 [ 8  9 10 11 12  5  4  3  2  1]]
f:
[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
g:
ndarray1: [[ 3  4  5  6  7 10  9  8  7  6]]
ndarray2: [[ 8  9 10 11 12  5  4  3  2  1]]
h:
ndarray1: [[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]
ndarray2: [[ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [ 9]
 [ 7]
 [ 5]
 [ 3]
 [ 1]]
i:
[ 3  8  4  9  5 10  6 11  7 12]
j:
[10  9  8  7  6  5  4  3  2  1]


In [15]:
import numpy as np
arr = np.random.randint(1, 101, size=100)

median = np.median(arr)
print("a:")
print("Median:", median)

variance = np.var(arr)
print("b:")
print("Variance:", variance)

max_idx = np.argmax(arr)
print("c:")
print("Index of maximum value:", max_idx)

min_idx = np.argmin(arr)
print("d:")
print("Index of minimum value:", min_idx)

condition_index = np.where((arr > 35) & (arr <= 90))[0]
print("e:")
print("Indices of values between 35 and 90:", condition_index)

a:
Median: 53.0
b:
Variance: 717.73
c:
Index of maximum value: 13
d:
Index of minimum value: 55
e:
Indices of values between 35 and 90: [ 2  3  4  7  8  9 15 16 17 19 21 22 25 26 27 29 30 31 32 34 36 37 39 40
 41 43 45 47 49 52 53 54 57 58 59 61 63 72 75 76 79 80 81 82 83 85 86 88
 89 90 91 92 94 95 96 97 99]
